email: matt.armour@gmail.com
description: >-
  A simple blog about computers and technology by Matt Armour.
baseurl: ""
url: "https://hzrd.sh"

github_username:  dkfx

#theme: type-on-strap
remote_theme: sylhare/Type-on-Strap
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

title: "HZRD"
avatar: assets/images/site/avatar.png
favicon: assets/images/site/favicon.ico
header_text: " "
header_feature_image: assets/images/site/header.jpg
footer_text: Copyright 2022-2025 Matt Armour. All Rights Reserved.<br>Powered by Jekyll with Type on Strap
color_theme: dark
excerpt: true
